version: "3.9"

services:
  api:
    image: ghcr.io/kimjeacheol/python-backend:latest
    container_name: python-backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - ENV=production
