version: "3.9"

services:
  api:
    image: ghcr.io/kimjeacheol/python-backend:latest
    container_name: python-backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - ENV=production
      - API_KEY=${API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FMP_BASE_URL=${FMP_BASE_URL}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
