version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: celery -A core.celery_app.celery_app worker --loglevel=INFO
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
